name: Building Docker Image

on:
  push:
    branches:
      - 'temp-deployment'

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker container
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ghcr.io/meitrex/docprocai_service:latest
          push: true
